# @see https://stefanzweifel.io/posts/2021/04/28/auto-merge-dependabot-pull-requests/
name: Automerge dependabot pull requests

on:
  workflow_run:
    types:
      - completed
    workflows:
      # "name" atrribute of workflows status to check
      - 'Tests'
      - 'Code formatting'

jobs:
  merge-me:
    name: Merge dependabot pull request

    runs-on: ubuntu-latest

    steps:
      - name: Merging PR
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: ridedott/merge-me-action@v2.9.12
        with:
          # Depending on branch prodtection rules, a  manually populated
          # `GITHUB_TOKEN_WORKAROUND` secret with permissions to push to
          # a protected branch must be used.
          #
          # When using a custom token, it is recommended to leave the following
          # comment for other developers to be aware of the reasoning behind it:
          #
          # This must be used as GitHub Actions token does not support pushing
          # to protected branches.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRESET: DEPENDABOT_MINOR
